=== vitorino87/Examples-Java-EE/tutorials/Java_EE_5_Tutorial/examples/coffeebreak/cb/dtds/coffee-order.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT coffee-order (orderID, customer, address, line-item+, total)>

<!ELEMENT orderID (#PCDATA)>

<!ELEMENT customer (last-name, first-name, phone-number, 
   email-address)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT phone-number (#PCDATA)>
<!ELEMENT email-address (#PCDATA)>

<!ELEMENT address (street, city, state, zip)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
 
<!ELEMENT line-item (coffee-name, pounds, price)>
<!ELEMENT coffee-name (#PCDATA)>
<!ELEMENT pounds (#PCDATA)>
<!ELEMENT price (#PCDATA)>
   
<!ELEMENT total (#PCDATA)>

=== vitorino87/Examples-Java-EE/tutorials/Java_EE_5_Tutorial/examples/coffeebreak/cb/dtds/coffee-order.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
 Copyright 2002 Sun Microsystems, Inc. All rights reserved.
 SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->


<!DOCTYPE coffee-order
    PUBLIC "-//Sun Microsystems, Inc.//DTD Coffee Order//EN"
    "http://java.sun.com/webservices/dtds/coffee-order.dtd">

<coffee-order>
    <orderID>
		"1234"
    </orderID>

    <customer>
        <last-name>
            "Pental"
        </last-name>
        <first-name>
            "Ragni"
        </first-name>
    </customer>

    <address>
        <street>
            "9876 Central Way"
        </street>
        <city>
            "Rainbow"
        </city>
        <state>
            "CA"
        </state>
        <zip>
            "99999"
        </zip>
        <phone-number>
            "908 873-6789"
        </phone-number>
        <email-address>
            "ragnip@aol.com"
        </email-address>
    </address>

    <line-item>
        <coffee-name>
            "arabica"
        </coffee-name>
        <pounds>
            "2"
        </pounds>
        <price>
            "10.95"
        </price>
    </line-item>

    <total>
        "10.95"
    </total>
   
</coffee-order>
