=== vitorino87/Examples-Java-EE/tutorials/Java_EE_5_Tutorial/examples/coffeebreak/cb/dtds/price-list.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT price-list (coffee+)>

<!ELEMENT coffee (coffee-name, price)>

<!ELEMENT coffee-name (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== vitorino87/Examples-Java-EE/tutorials/Java_EE_5_Tutorial/examples/coffeebreak/cb/dtds/price-list.xml
<!DOCTYPE price-list
    PUBLIC "-//Sun Microsystems, Inc.//DTD priceList//EN"
    "http://java.sun.com/webservices/dtds/price-list.dtd">

<price-list
    <coffee>
		<coffee-name> Arabica </coffee-name>
		<price> 4.50 </price>
    </coffee>

    <coffee>
		<coffee-name> HouseBlend </coffee-name>
		<price> 5.00 </price>
    </coffee>

    <coffee>
		<coffee-name> Espresso </coffee-name>
		<price> 5.00 </price>
    </coffee>

    <coffee>
		<coffee-name> Dorada </coffee-name>
		<price> 6.00 </price>
    </coffee>

</price-list>
